/*
-- Query: SELECT * FROM project_ojt_2.users
LIMIT 0, 1000

-- Date: 2023-03-27 11:45
*/
INSERT INTO `` (`userId`,`address`,`avatar`,`birtDate`,`city`,`country`,`email`,`firstName`,`lastName`,`passwords`,`phone`,`ranking`,`state`,`userName`,`userStatus`,`password`,`blockedDate`) VALUES (1,'HN','img 1','2023-03-17','HN','HN','abc@gmail.com','Nguyen ','Van A','123','0114785336',1,'HN','test','0','123','2023-03-22');
INSERT INTO `` (`userId`,`address`,`avatar`,`birtDate`,`city`,`country`,`email`,`firstName`,`lastName`,`passwords`,`phone`,`ranking`,`state`,`userName`,`userStatus`,`password`,`blockedDate`) VALUES (2,'TDP Kiều Mai','img 1','1999-02-10','Hà Nội','Viet Nam','testcode@gmail.com','Minh Thoa','Nguyễn',NULL,'0968686868',0,'Bắc Từ liêm','admin','1','$2a$10$gYD0eFa8Uf7MI4gsCJ.Ng.WMBpPP1V27oJhTuVLDcA7TqSmUBswYi',NULL);
INSERT INTO `` (`userId`,`address`,`avatar`,`birtDate`,`city`,`country`,`email`,`firstName`,`lastName`,`passwords`,`phone`,`ranking`,`state`,`userName`,`userStatus`,`password`,`blockedDate`) VALUES (3,'TDP Kiều Mai','img 1','1999-02-10','Hà Nội','Viet Nam','testcode123@gmail.com','Minh Thoa','Nguyễn',NULL,'0968686868',0,'Bắc Từ liêm','user','1','$2a$10$skkUGIMx7u2VpMNqqLF3DO7IW9AUkHYnwl3F/Qvn3jZvSshHeEmHe',NULL);
INSERT INTO `` (`userId`,`address`,`avatar`,`birtDate`,`city`,`country`,`email`,`firstName`,`lastName`,`passwords`,`phone`,`ranking`,`state`,`userName`,`userStatus`,`password`,`blockedDate`) VALUES (4,'TDP Kiều Mai','img 1','1999-02-10','Hà Nội','Viet Nam','testcode1@gmail.com','Minh Thoa','Nguyễn',NULL,'0968686868',0,'Bắc Từ liêm','moderator','1','$2a$10$MJc43AdcgqmTEtsv2r8O6.I/Zm8yg2CYwRixFGn9I5E4bGirJkL4y',NULL);
INSERT INTO `` (`userId`,`address`,`avatar`,`birtDate`,`city`,`country`,`email`,`firstName`,`lastName`,`passwords`,`phone`,`ranking`,`state`,`userName`,`userStatus`,`password`,`blockedDate`) VALUES (5,'TDP Kiều Mai','img 1','1999-02-10','Hà Nội','Viet Nam','testcodepc@gmail.com','Minh Thoa','Nguyễn',NULL,'0968686868',0,'Bắc Từ liêm','moderatorpc','1','$2a$10$1OladAY2pPBltfRMSsGZp.TN5moAY7qpnjIGdWPK552e733UHqXma',NULL);
INSERT INTO `` (`userId`,`address`,`avatar`,`birtDate`,`city`,`country`,`email`,`firstName`,`lastName`,`passwords`,`phone`,`ranking`,`state`,`userName`,`userStatus`,`password`,`blockedDate`) VALUES (6,'TDP Kiều Mai','img 1','1999-02-10','Hà Nội','Viet Nam','testcodeadd@gmail.com','Minh Thoa','Nguyễn',NULL,'0968686868',0,'Bắc Từ liêm','addNewAdmin','0','$2a$10$K9v/rBDiTyrl32oxPqe6W.NCXdSy0aJYHQDdsporrFd4GxVkqUYvW',NULL);
INSERT INTO `` (`userId`,`address`,`avatar`,`birtDate`,`city`,`country`,`email`,`firstName`,`lastName`,`passwords`,`phone`,`ranking`,`state`,`userName`,`userStatus`,`password`,`blockedDate`) VALUES (7,'TDP Kiều Mai','img 1','1993-02-10','Hà Nội','Viet Nam','testcodeadduserupdate@gmail.com','Thanh PC','Pham',NULL,'0968686868',0,'Bắc Từ liêm','addNewAdminTest','1','$2a$10$4FeTTybGRzGt/d1ZIPta9u8yg16O/0kldPchZ5Q4m4xwUSWIeEcVW',NULL);
INSERT INTO `` (`userId`,`address`,`avatar`,`birtDate`,`city`,`country`,`email`,`firstName`,`lastName`,`passwords`,`phone`,`ranking`,`state`,`userName`,`userStatus`,`password`,`blockedDate`) VALUES (8,'TDP Kiều Mai','img 1','1999-02-10','Hà Nội','Viet Nam','testcodeadduser@gmail.com','Minh Thoa','Nguyễn',NULL,'0968686868',0,'Bắc Từ liêm','addNewUserTest','1','$2a$10$565YGOlfd.HMEiazJgg7ouLp9unvYWk4X7Ra5eGWuStbSZpMFwEIK',NULL);
